version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/install_nginx.sh
  AfterInstall:
    - location: scripts/start_nginx.sh
      timeout: 180
      runas: root